### ISSUE TITLE
figure out hamburguer menu for small screens for top right

### ISSUE THREAD

**Issue by lucharo** [lucharo/lucharo.github.io#5]
check convo w/ claude:

To turn the three buttons on the right into a menu on small screens, you can use a responsive design approach. Here are the general steps you can take:

1. Create a hamburger icon (three horizontal lines) that will serve as the toggle for the menu on small screens.

2. Initially, hide the three buttons and display the hamburger icon only on small screens using media queries or CSS classes.

3. When the hamburger icon is clicked, toggle the visibility of the three buttons to display them as a dropdown menu.

4. You can achieve this using JavaScript or CSS (e.g., toggling a CSS class that shows/hides the menu).

5. Make sure the menu items stack vertically on small screens and maintain their horizontal layout on larger screens.

6. Ensure the menu is responsive and adjusts its layout based on the screen size to provide the best user experience.

Here's an example of how you can implement this using a combination of HTML, CSS, and JavaScript:

HTML:
```html
<header>
  <div class="logo">Luis Chaves Rodriguez</div>
  <nav>
    <div class="hamburger-icon">&#9776;</div>
    <ul class="menu">
      <li><a href="#">About</a></li>
      <li><a href="#">Resources I have enjoyed</a></li>
      <li><a href="#">Search</a></li>
    </ul>
  </nav>
</header>
```

CSS:
```css
/* Small screens */
@media (max-width: 767px) {
  .menu {
    display: none;
  }
  .hamburger-icon {
    display: block;
  }
}

/* Large screens */
@media (min-width: 768px) {
  .menu {
    display: flex;
    justify-content: flex-end;
  }
  .menu li {
    margin-left: 20px;
  }
  .hamburger-icon {
    display: none;
  }
}

/* Common styles */
.hamburger-icon {
  cursor: pointer;
}
.menu.show {
  display: flex;
  flex-direction: column;
}
```

JavaScript:
```javascript
const hamburgerIcon = document.querySelector('.hamburger-icon');
const menu = document.querySelector('.menu');

hamburgerIcon.addEventListener('click', () => {
  menu.classList.toggle('show');
});
```

This example uses media queries to hide the menu and show the hamburger icon on small screens. When the hamburger icon is clicked, the JavaScript code toggles the 'show' class on the menu, which displays the menu items in a vertical layout. On larger screens, the menu is displayed horizontally without the hamburger icon.

You can further customize the styles and behavior to fit your specific design requirements.
